accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "CDLA-Permissive-2.0",
]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
workarounds = ["ring", "rustls"]
private = { ignore = true }
